# Splegg Module Settings

file_version: 1
# Visual representation in menus
menus:
  vote:
    item: EGG

# Game items (optional)
items:
  # Items to give players on game start
  # Format: MATERIAL:AMOUNT:SLOT
  starting_items:
    - "DIAMOND_SHOVEL:1:0"

# Potion effects (optional)
effects:
  # Effects to give players during the game
  # Format: EFFECT_TYPE:DURATION_TICKS:AMPLIFIER
  starting_effects: []

  # Effects when player respawns
  # Format: EFFECT_TYPE:DURATION_TICKS:AMPLIFIER
  respawn_effects:
    - "DAMAGE_RESISTANCE:60:1"
